[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://invoicing-roi-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200